# Made to be run alone, or extended in another Grafana docker-compose setup! Refer to README.md
# https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
    # REMEMBER, any port below 1024 is privileged and should not be used!
    # https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html
      - "12345:12345" # web interface
      # the following ports are largely chosen following Graylog docker-compose defaults during migration, no other reason
      # https://github.com/Graylog2/docker-compose/blob/b787fc8ccecbe2ddcac01d220e6c17ff89d73507/open-core/docker-compose.yml#L63-L66
      - "5140:5140/tcp" # syslog
      # - "5140:5140/udp" # syslog
      - "5555:5555" # raw http
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - type: bind
        source: ./config.alloy
        target: /etc/alloy/config.alloy
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-1
    restart: unless-stopped
    ports:
      - '13000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
