services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
      - "5140:5140/tcp" # syslog
      - "5140:5140/udp" # syslog
      - "5555:5555" # raw http
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - type: bind
        source: ./config.alloy
        target: /etc/alloy/config.alloy
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-1
    restart: unless-stopped
    ports:
      - '13000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
