services:
  alloy-docker-forwarder:
    image: grafana/alloy:latest
    container_name: alloy-docker-forwarder
    ports:
      - "12345:12345" # web interface
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--storage.path=/var/lib/alloy/data",
        "/etc/alloy/config.alloy",
      ]
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
